name: vm

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download
      run: Invoke-WebRequest 'https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe' -OutFile 'cloudflared.exe'

    - name: Enable Terminal Server
      run: Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server' -Name 'fDenyTSConnections' -Value 0

    - name: Set Firewall Rule
      run: Enable-NetFirewallRule -DisplayGroup 'Remote Desktop'

    - name: Enable User Authentication
      run: Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name 'UserAuthentication' -Value 1

    - name: Set Password
      run: Set-LocalUser -Name 'runneradmin' -Password (ConvertTo-SecureString -AsPlainText '${{ secrets.PASSWORD }}' -Force)

    - name: Adjust Performance Priority
      run: Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\PriorityControl' -Name 'Win32PrioritySeparation' -Value 38

    - name: Start cloudflared
      run: .\cloudflared.exe tunnel --url rdp://localhost:3389
